### ISSUE TITLE
Doesn't work with FMOD Studio 1.08.08

### ISSUE THREAD

**Issue by mstop4** [mstop4/FMODGMS#2]
Crashes in fmod.dll. ~~No idea why right now.~~

fmod-nick:
> There's an issue with FFT window sizes less than the DSP blocksize. We'll get it fixed in 1.08.10.

Works with 1.08.07.

**Comment by fmod-nick** [comment]
There's an issue with FFT window sizes less than the DSP blocksize. We'll get it fixed in 1.08.10.

**Comment by mstop4** [comment]
OK, thanks for the info.
