### ISSUE TITLE
Issues with FMODGMS and GMS2

### ISSUE THREAD

**Issue by mstop4** [mstop4/FMODGMS#5]
FMODGMS does not work during testing (e.g. if the game is run within the GMS2 IDE using the "Run" or "Debug" commands.

However, it does run properly after the game is build as a standalone executable and launched outside of GMS2.

**Comment by Grix** [comment]
Isn't this probably a problem with GMS2 and not FMODGMS? Have you tried submitting a GM bug report to see what they think?

**Comment by mstop4** [comment]
As of v2.0.5.77, there is only one case where the extension fails to load on Windows machines: testing via the VM. Ubuntu is still to be tested.

**Comment by gwartney21** [comment]
I seem to still get this issue when trying to run it. When i go to run it to test the game or even in debug mode I get the Error fmodgms was not loaded properly. But if i build the game it does work. Not sure if there is a work around for this or if iam just not using the program correctly?

**Comment by mstop4** [comment]
I'm getting the same errors as well. I'm still figuring out why it doesn't work on Run/Debug with the VM. It does work if you Run it with the YYC.

**Comment by gwartney21** [comment]
Ah ok well at least i know its not just on my end. Thanks for letting me know.

**Comment by Grix** [comment]
The GMS 2.1 runtime release notes say: "Improved DLL dependency checking/loading for runs (was fine when doing create executable)"

I haven't tested but maybe that means that this is now fixed?

**Comment by mstop4** [comment]
@Grix Hey, thanks for the heads-up. I just tested the problem case (VM from within the IDE) and it seems to be working fine now. I'm glad the problem has been finally resolved. and a bit relieved that the problem wasn't on my end, as I had no idea why it wasn't working.

**Comment by mstop4** [comment]
@Grix One more thing, can you point to me where in the release notes you found that line? Thanks.

**Comment by Grix** [comment]
@mstop4 It's in the runtime release notes here, the last item under "Windows": http://gms.yoyogames.com/release-notes-runtime.html

Note that these runtime release notes is to be separate from the IDE GMS2 release notes here: http://gms.yoyogames.com/ReleaseNotes.html
I don't know why
