### ISSUE TITLE
Understanding problem

### ISSUE THREAD

**Issue by gq-omistarz** [mstop4/FMODGMS#6]
We are looking into using FMOD or Wwise in a GameMaker project. Your example seems to be heavily music focused. Is this extension meant to be used for interactive projects (events, listeners, 3D sounds, etc.)? Can you import a large FMOD project and trigger parameterized events with this extension?

Cheers!

**Comment by mstop4** [comment]
Hi there, sorry for the late reply/

Right now, FMODGMS is more focused on simply playing background music in a wide variety of formats. If there is a need for it, I might consider adding support for events and 3D sounds.
