### ISSUE TITLE
Questions about the rewrite

### ISSUE THREAD

**Issue by Grix** [mstop4/FMODGMS#8]
Hi,
I have finally started the work on migrating to this sound engine in one of my programs, but I just noticed that you have opened a new branch for a refactor. So I have two questions:

- Will the refactored extension be compatible with the old one (same function names etc)? Or should I wait to migrate until the refactor is done so I don't have to change everything again once the new version is out?

- I want to contribute a bit more code to this project, should I also wait until you are done with the refactor and then add a pull request, or is it better to start right away and add a pull request on the current/legacy branch? 
(specifically I need to implement a way to pass flags such as FMOD_ACCURATETIME to the LoadSound/Stream function, and eventually add functionality to do FFT on a whole song at once instead of only getting instantaneous data during playback).

Sorry if creating an issue to ask this was inappropriate, I couldn't find a more elegant way to contact you.

**Comment by mstop4** [comment]
@Grix 

Thanks for your continued interest in FMODGMS. To answer your questions:

* I'm debating whether to change the function names from using mixed Pascal and camel case (FMOD Studio's style) to just pure camel case (GML's style). I've have some users comment about the "unnecessary capitalization" in the function names. Of course, this change would break all legacy code.

* Most of my experimenting is currently in the [FMOD Studio Sandbox](https://github.com/mstop4/fmod-studio-sandbox), I'm trying to organize all the extension's variables and/or functions into a class, namespace, or struct and figure out if this is possible given GMS's limited interface with DLLs.  The sandbox is where I'll also experiment with the HTML5 version of FMOD Studio to see if I can get it working with web games.

* If you want to add new features and submit a pull request, you can do that now. currently, I'm just playing around in the sandbox repo and won't make changes to this repo until I'm sure of my plans.

**Comment by Grix** [comment]
I see, thanks for the answers!
